import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Blog Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container px-4 pt-5">
        <h1 className="mt-4">Bienvenue sur Code.io</h1>
        <span>Le blog communautaire des aficionados de développement web.</span>

        <div className="row mt-5">
          <div className="col-12 col-sm-6" style={{minHeight: "200px"}}>
            <div className="card w-100 h-100">
              <div className="card-body">
                <h5 className="card-title">Lisez les articles</h5>
                <h6 className="card-subtitle mb-2 text-muted">
                  Maximiser votre culture web
                </h6>
                <p className="card-text">
                  Chaque auteur tente de vous apporter le plus de valeur
                  possible.
                </p>
                <Link className="card-link" href="/blog">
                  Visiter le blog
                </Link>
              </div>
            </div>
          </div>

          <div className="col-12 col-sm-6" style={{minHeight: "200px"}}>
            <div className="card w-100 h-100">
              <div className="card-body">
                <h5 className="card-title">Faites un tour vers la liste de membres</h5>
                <h6 className="card-subtitle mb-2 text-muted">
                  Rencontrez des devs
                </h6>
                <p className="card-text">
                  Ajoutez, invitez et discutez avec les différents membres
                </p>
                <Link className="card-link" href="/utilisateurs">
                  Découvrez la liste des membres
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
